spring.application.name=vellora
spring.datasource.url=jdbc:postgresql://localhost:5432/vellora
spring.datasource.username=postgres
spring.datasource.password=taehyung
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
