spring.application.name=vellora
spring.datasource.url=jdbc:postgresql://localhost:5432/vellora
spring.datasource.username=postgres
spring.datasource.password=taehyung
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
jwt.secret=vellora-super-secret-key-change-this-later-min-32-characters-long
jwt.expiration-ms=86400000
